---

# Installs packages/dependencies for web servers

- hosts: all

  pre_tasks:
    - name: Gather EC2 facts
      action: ec2_facts
      when: staging

- hosts: app-servers

  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "driver.windshaft" }
    - { role: "driver.app" }
    - { role: "driver.nginx" }

- hosts: database-servers

  become: True

  roles:
    - { role: "driver.access" }
